package audio_player

const (
	REPLACE_ALL      = "REPLACE_ALL"
	REPLACE_ENQUEUED = "REPLACE_ENQUEUED"
	ENQUEUE          = "ENQUEUE"

	AUDIO_MP3  = "AUDIO_MP3"
	AUDIO_M3U8 = "AUDIO_M3U8"
	AUDIO_M4A  = "AUDIO_M4A"

	AUDIO_TYPE_MUSIC = "MUSIC"

	LYRIC_FORMAT_LRC = "LRC"
)
